// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpjZyKVwcgYTFuR370qM2cILfJNXTA1Cw',
    appId: '1:873816340121:web:f0f22197e8c0d55493ea08',
    messagingSenderId: '873816340121',
    projectId: 'order-tracker-fa5e9',
    authDomain: 'order-tracker-fa5e9.firebaseapp.com',
    storageBucket: 'order-tracker-fa5e9.firebasestorage.app',
    measurementId: 'G-9NMYM940M7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXxLdxksdtAPtt4KCfqLWIFdKeU4qzKDE',
    appId: '1:873816340121:ios:48bcbd7b184ea23493ea08',
    messagingSenderId: '873816340121',
    projectId: 'order-tracker-fa5e9',
    storageBucket: 'order-tracker-fa5e9.firebasestorage.app',
    iosBundleId: 'com.example.paamyOrderTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXxLdxksdtAPtt4KCfqLWIFdKeU4qzKDE',
    appId: '1:873816340121:ios:48bcbd7b184ea23493ea08',
    messagingSenderId: '873816340121',
    projectId: 'order-tracker-fa5e9',
    storageBucket: 'order-tracker-fa5e9.firebasestorage.app',
    iosBundleId: 'com.example.paamyOrderTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqSY430yE3LqDwiteROz1r-TvfDONuGf4',
    appId: '1:873816340121:android:751cfb6ad0d73f3393ea08',
    messagingSenderId: '873816340121',
    projectId: 'order-tracker-fa5e9',
    storageBucket: 'order-tracker-fa5e9.firebasestorage.app',
  );

}